events {
    worker_connections 1024;
}

http {
    upstream backend_app {
        # Docker DNS resolut le nom de service 'web' vers toutes les IP des conteneurs du replica
        server web:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
